// Generated by build-wordpress-embed.py - do not edit.
// Identical to app.js except the inventory URL is absolute, so the
// script can be loaded from a page on another domain.
// K-12 AI Inventory Browser
// Loads k12_inventory_latest.csv (v18 base + newly discovered resources)

const state = {
  resources: [],
  filtered: [],
  search: '',
  // Default view is newest-first; the Date header toggles direction.
  sortBy: 'effectiveDate',
  sortAsc: false,
  scannedAt: new Date().toISOString()
};

const els = {
  resourceTypeSelect: document.querySelector("#resourceTypeSelect"),
  subjectSelect: document.querySelector("#subjectSelect"),
  gradeBandSelect: document.querySelector("#gradeBandSelect"),
  sourceSelect: document.querySelector("#sourceSelect"),
  verificationSelect: document.querySelector("#verificationSelect"),
  licenseToggle: document.querySelector("#licenseToggle"),
  resultsList: document.querySelector("#resultsList"),
  exportButton: document.querySelector("#exportButton"),
  totalCount: document.querySelector("#totalCount"),
  highFitCount: document.querySelector("#highFitCount"),
  datasetCount: document.querySelector("#datasetCount"),
  benchmarkCount: document.querySelector("#benchmarkCount"),
  modelCount: document.querySelector("#modelCount"),
  viewTitle: document.querySelector("#viewTitle"),
  scanMeta: document.querySelector("#scanMeta"),
  viewMeta: document.querySelector("#viewMeta"),
  reloadButton: document.querySelector("#reloadButton"),
  searchInput: document.querySelector("#searchInput"),
  searchClear: document.querySelector("#searchClear")
};

// Parse CSV line properly handling quoted fields
function parseCSVLine(line) {
  const result = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    const nextChar = line[i + 1];

    if (char === '"') {
      if (inQuotes && nextChar === '"') {
        // Escaped quote
        current += '"';
        i++;
      } else {
        // Toggle quote state
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      result.push(current.trim().replace(/^"(.*)"$/, '$1'));
      current = '';
    } else {
      current += char;
    }
  }
  result.push(current.trim().replace(/^"(.*)"$/, '$1'));
  return result;
}

// Load and parse CSV
function loadInventory() {
  const v = 'v132-' + Date.now();
  fetch('https://xweidp.github.io/k12-ai-scanner/data/k12_inventory_latest.csv?v=' + v)
    .then(r => {
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return r.text();
    })
    .then(csv => {
      const rows = parseFullCSV(csv);
      if (rows.length < 2) {
        showError('CSV file is empty');
        return;
      }

      const headers = rows[0];
      console.log('CSV Headers:', headers);

      state.resources = rows.slice(1).map((values, idx) => {
        const row = {};
        headers.forEach((h, i) => {
          row[h] = values[i] || '';
        });

        const resourceType = row.resource_subtype || 'Dataset';
        // subject_canonical is written by consolidate-subjects.py. Fall back to
        // the raw field so the page still works on an un-consolidated CSV.
        const subject = row.subject_canonical || row.subject_area || 'Cross-subject / General';
        const source = row.discovery_source || row.author_name || 'Curated';

        const publicationDate = row.publication_date || '';
        const discoveryDate = row.discovery_date || '';

        const rec = {
          id: row.record_id || `r-${idx}`,
          title: row.resource_name || 'Untitled',
          resourceType: resourceType,
          source: source,
          subject: subject,
          gradeBand: row.grade_span_group || 'K-12',
          license: row.license_status_clean || 'Not listed',
          // short_description is built by generate-descriptions.py: a plain
          // sentence saying what the resource IS. The old fallback chain here
          // surfaced provenance notes ("Hugging Face dataset repository URL
          // plus retained dataset inventory row"), which told readers nothing.
          description: row.short_description || row.description
                       || row.educational_use_case || '',
          url: row.url || '',
          publicationDate: publicationDate,
          discoveryDate: discoveryDate,
          // Every row gets a sortable date: when we don't know the publication
          // date, fall back to when the scanner first saw it.
          effectiveDate: publicationDate || discoveryDate || '',
          dateIsPublication: Boolean(publicationDate),
          readinessTier: row.final_readiness_index_tier || 'Not Reviewed',
          isDownloadable: row.is_downloadable === 'True' || row.is_downloadable === true,
          verificationNote: row.verification_note || '',
          fit: parseInt(row.fit_score) || 50
        };

        // Precomputed lowercase haystack so search doesn't rebuild it per keystroke.
        rec.searchBlob = [
          rec.title, rec.resourceType, rec.subject, rec.source,
          rec.license, rec.description, rec.gradeBand
        ].join(' ').toLowerCase();

        return rec;
      });

      console.log(`Loaded ${state.resources.length} resources`);
      const withDates = state.resources.filter(r => r.publicationDate).length;
      console.log(`Resources with publication dates: ${withDates}`);

      // Debug: show Bridge record if found
      const bridge = state.resources.find(r => r.title && r.title.includes('Bridge'));
      if (bridge) {
        console.log(`Bridge found:`, {
          title: bridge.title,
          publicationDate: bridge.publicationDate,
          url: bridge.url
        });
      }
      applyFilters();
      render();
    })
    .catch(err => {
      console.error('Load error:', err);
      showError(`Failed to load inventory: ${err.message}`);
    });
}

function showError(msg) {
  if (els.resultsList) {
    els.resultsList.innerHTML = `<div class="empty-state"><h2>Error: ${msg}</h2></div>`;
  }
}

function applyFilters() {
  const resourceType = els.resourceTypeSelect?.value || 'all';
  const subject = els.subjectSelect?.value || 'all';
  const gradeBand = els.gradeBandSelect?.value || 'all';
  const source = els.sourceSelect?.value || 'all';
  const verification = els.verificationSelect?.value || 'all';
  const licenseOpen = els.licenseToggle?.checked;

  const isVerified = r => r.readinessTier && !r.readinessTier.includes('Not Reviewed');

  // Multi-word search: every term must appear somewhere in the record.
  const terms = state.search.toLowerCase().split(/\s+/).filter(Boolean);

  state.filtered = state.resources.filter(r => {
    if (resourceType !== 'all' && r.resourceType !== resourceType) return false;
    if (subject !== 'all' && r.subject !== subject) return false;
    if (gradeBand !== 'all' && r.gradeBand !== gradeBand) return false;
    if (source !== 'all' && r.source !== source) return false;
    if (licenseOpen && /^not|^see|^custom|^unknown/i.test(r.license)) return false;

    // Verification filter
    if (verification === 'verified' && !isVerified(r)) return false;
    if (verification === 'new' && isVerified(r)) return false;

    if (terms.length && !terms.every(t => r.searchBlob.includes(t))) return false;

    return true;
  });

  applySorting();
  populateSelects();
  render();
}

const DATE_FIELDS = ['effectiveDate', 'publicationDate', 'discoveryDate'];

function applySorting() {
  if (!state.sortBy) return;

  const isDate = DATE_FIELDS.includes(state.sortBy);

  state.filtered.sort((a, b) => {
    let aVal = a[state.sortBy];
    let bVal = b[state.sortBy];

    if (isDate) {
      aVal = aVal ? new Date(aVal).getTime() : 0;
      bVal = bVal ? new Date(bVal).getTime() : 0;
      // Undated rows sink to the bottom in either direction rather than
      // hijacking the top of a newest-first list.
      if (!aVal && !bVal) return 0;
      if (!aVal) return 1;
      if (!bVal) return -1;
    } else if (typeof aVal === 'string') {
      aVal = aVal.toLowerCase();
      bVal = String(bVal || '').toLowerCase();
    }

    if (aVal < bVal) return state.sortAsc ? -1 : 1;
    if (aVal > bVal) return state.sortAsc ? 1 : -1;
    return 0;
  });
}

function populateSelects() {
  // Subjects (canonical buckets only - see consolidate-subjects.py)
  const subjects = [...new Set(state.resources.map(r => r.subject))].filter(Boolean).sort();
  const subjectValue = els.subjectSelect?.value || 'all';
  if (els.subjectSelect) {
    els.subjectSelect.innerHTML = [
      '<option value="all">All subjects</option>',
      ...subjects.map(s => `<option value="${esc(s)}">${esc(s)}</option>`)
    ].join('');
    els.subjectSelect.value = subjectValue;
  }

  // Sources
  const sources = [...new Set(state.resources.map(r => r.source))].sort();
  const sourceValue = els.sourceSelect?.value || 'all';
  if (els.sourceSelect) {
    els.sourceSelect.innerHTML = [
      '<option value="all">All sources</option>',
      ...sources.map(s => `<option value="${esc(s)}">${esc(s)}</option>`)
    ].join('');
    els.sourceSelect.value = sourceValue;
  }
}

function render() {
  const counts = {
    total: state.filtered.length,
    high: state.filtered.filter(r => r.fit >= 70).length,
    dataset: state.filtered.filter(r => r.resourceType === 'Dataset').length,
    benchmark: state.filtered.filter(r => r.resourceType === 'Benchmark').length,
    model: state.filtered.filter(r => r.resourceType === 'Model').length
  };

  if (els.totalCount) els.totalCount.textContent = counts.total;
  if (els.highFitCount) els.highFitCount.textContent = counts.high;
  if (els.datasetCount) els.datasetCount.textContent = counts.dataset;
  if (els.benchmarkCount) els.benchmarkCount.textContent = counts.benchmark;
  if (els.modelCount) els.modelCount.textContent = counts.model;

  const verified = state.filtered.filter(r => !r.readinessTier?.includes('Not Reviewed')).length;
  const newCount = state.filtered.filter(r => r.readinessTier?.includes('Not Reviewed')).length;

  if (els.scanMeta) {
    els.scanMeta.textContent = '';
  }

  if (els.viewTitle) {
    els.viewTitle.textContent = counts.total
      ? `${counts.total} K-12 resources`
      : state.resources.length > 0
        ? 'No resources match filters'
        : 'Loading...';
  }

  if (els.viewMeta) {
    const parts = [`${counts.dataset} datasets`, `${counts.benchmark} benchmarks`, `${counts.model} models`];
    if (state.search) {
      parts.push(`matching “${state.search}”`);
    } else if (counts.total !== state.resources.length) {
      parts.push(`of ${state.resources.length} total`);
    }
    els.viewMeta.textContent = parts.join(', ');
  }

  if (!counts.total) {
    if (els.resultsList) {
      const msg = state.resources.length === 0
        ? 'Loading inventory...'
        : state.search
          ? `No resources match “${esc(state.search)}”.`
          : 'No resources match your filters.';
      els.resultsList.innerHTML = `<div class="empty-state"><h2>${msg}</h2></div>`;
    }
    return;
  }

  if (els.resultsList) {
    els.resultsList.innerHTML = state.filtered.map(renderRow).join('');
  }
}

function renderRow(r) {
  const badge = r.readinessTier?.includes('Not Reviewed')
    ? '<span class="discovery-badge">NEW</span>'
    : '<span class="verified-badge">VERIFIED</span>';

  // "✓ Downloadable" on nearly every row is noise; only flag the exceptions.
  const caveat = (!r.isDownloadable && r.verificationNote)
    ? `<span class="row-caveat">⚠ ${esc(r.verificationNote)}</span>`
    : '';

  return `
    <article class="result-row">
      <div class="table-cell opportunity-cell">
        <p class="opportunity-title">
          ${r.url ? `<a href="${esc(r.url)}" target="_blank">${esc(r.title)}</a>` : esc(r.title)}
        </p>
        <p class="meta">${badge}</p>
      </div>
      <div class="table-cell">${esc(prettyType(r.resourceType))}</div>
      <div class="table-cell">${esc(r.subject) || 'Cross-subject / General'}</div>
      <div class="table-cell">${esc(r.source)}</div>
      <div class="table-cell">${renderDate(r)}</div>
      <div class="table-cell">${esc(r.license)}</div>
      <div class="table-cell description-cell">
        <span class="row-description">${esc(r.description)}</span>
        ${caveat}
      </div>
    </article>
  `;
}

// Resource subtypes are stored snake_case (e.g. "Research_Paper"); display them
// with spaces so they wrap cleanly instead of breaking mid-word.
function prettyType(t) {
  return String(t || '').replace(/_/g, ' ');
}

// Show the publication date when we know it. Otherwise show when the scanner
// first found the resource, labelled so the two aren't confused.
function renderDate(r) {
  if (r.dateIsPublication) {
    return `<span class="date-published">${esc(r.publicationDate)}</span>`;
  }
  if (r.discoveryDate) {
    return `<span class="date-added" title="Publication date unknown; this is when the scanner first found it">added ${esc(r.discoveryDate)}</span>`;
  }
  return '<span class="date-unknown">—</span>';
}

function esc(s) {
  const map = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };
  return String(s || '').replace(/[&<>"']/g, c => map[c]);
}

function exportCsv() {
  if (!state.filtered.length) return;
  const header = ['Title', 'Type', 'Subject', 'Grade Band', 'Source', 'License',
                  'Published', 'Date Added', 'URL', 'Status'];
  const rows = state.filtered.map(r => [
    r.title, r.resourceType, r.subject, r.gradeBand, r.source, r.license,
    r.publicationDate, r.discoveryDate, r.url, r.readinessTier
  ]);
  const csv = [header, ...rows]
    .map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    .join('\n');

  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `k12-inventory-${new Date().toISOString().split('T')[0]}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// Event listeners
els.resourceTypeSelect?.addEventListener('change', applyFilters);
els.subjectSelect?.addEventListener('change', applyFilters);
els.gradeBandSelect?.addEventListener('change', applyFilters);
els.sourceSelect?.addEventListener('change', applyFilters);
els.verificationSelect?.addEventListener('change', applyFilters);
els.licenseToggle?.addEventListener('change', applyFilters);
els.exportButton?.addEventListener('click', exportCsv);
els.reloadButton?.addEventListener('click', loadInventory);

// Search: debounced so typing stays smooth on the full inventory.
let searchTimer;
els.searchInput?.addEventListener('input', () => {
  clearTimeout(searchTimer);
  searchTimer = setTimeout(() => {
    state.search = els.searchInput.value.trim();
    if (els.searchClear) els.searchClear.hidden = !state.search;
    applyFilters();
  }, 150);
});

els.searchClear?.addEventListener('click', () => {
  if (els.searchInput) els.searchInput.value = '';
  state.search = '';
  els.searchClear.hidden = true;
  applyFilters();
  els.searchInput?.focus();
});

// Escape clears the search while focus is in the box.
els.searchInput?.addEventListener('keydown', e => {
  if (e.key === 'Escape' && els.searchInput.value) {
    e.preventDefault();
    els.searchClear?.click();
  }
});

// Sort button click handler
document.querySelectorAll('.sort-btn').forEach(btn => {
  btn.addEventListener('click', (e) => {
    e.preventDefault();
    const sortField = btn.dataset.sort;
    if (state.sortBy === sortField) {
      state.sortAsc = !state.sortAsc;
    } else {
      state.sortBy = sortField;
      state.sortAsc = false; // Newest first by default
    }
    applyFilters();
  });
});

// Parse full CSV respecting multiline quoted fields
function parseFullCSV(csvText) {
  const rows = [];
  let row = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < csvText.length; i++) {
    const char = csvText[i];
    const nextChar = csvText[i + 1];

    if (char === '"') {
      if (inQuotes && nextChar === '"') {
        // Escaped quote
        current += '"';
        i++;
      } else {
        // Toggle quote state
        inQuotes = !inQuotes;
      }
    } else if (char === ',' && !inQuotes) {
      // Field separator
      row.push(current.trim().replace(/^"(.*)"$/s, '$1'));
      current = '';
    } else if ((char === '\n' || char === '\r') && !inQuotes) {
      // Row separator
      if (current || row.length) {
        row.push(current.trim().replace(/^"(.*)"$/s, '$1'));
        if (row.some(v => v)) {
          rows.push(row);
        }
        row = [];
        current = '';
      }
      if (char === '\r' && nextChar === '\n') i++;
    } else {
      current += char;
    }
  }

  if (current || row.length) {
    row.push(current.trim().replace(/^"(.*)"$/s, '$1'));
    if (row.some(v => v)) {
      rows.push(row);
    }
  }

  return rows;
}

// Load on page load
loadInventory();
