name = "k12-ai-scanner"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
vars = { ENVIRONMENT = "production" }

[triggers]
crons = ["0 13 * * 1"]

[[triggers.crons]]
cron = "0 13 * * 1"
